apiVersion: v1
kind: Pod
metadata:
  name: nginx-node-selector
  namespace:
  labels:
    run: nginx
spec:
  nodeSelector:
    hpc: true
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
