apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace:
  labels:
spec:
  tolerations:
  - key: node-type
    operator: Equal
    value: "production"
    effect: NoSchedule
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
