apiVersion: v1
kind: Pod
metadata:
  name: gpu
  namespace:
  labels:
    run: nginx
spec:
  nodeSelector:
    gpu: true
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
