apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: website
  namespace:
  labels:
    app: website
spec:
  replicas: 3
  selector:
    matchLabels:
      app: website
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: website
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - website
              topologyKey: kubernetes.io/hostname
      containers:
      - image: centos/httpd:latest
        imagePullPolicy: IfNotPresent
        name: flask
        ports:
        - containerPort: 80
          protocol: TCP
      dnsPolicy: ClusterFirst
